FORMAT: 1A
HOST: http://www.google.com

# Name

## Schema [/schema]

### Update a Shipment [PUT]
Modify an existing shipment.

+ Request (application/json)
    
    + Headers
        
            Authorization: Token 3e47b75000b0924b6c9ba5759a7cf15d

    + Body
    
            {
                "status": "IN_TRANSIT_TO_ORIGIN"
            }
            
    + Schema

            {
                "title": "Shipment",
                "description": "A Badger shipment resource",
                "type": "object"
                "properties": {
                    "status": {
                        "description": "Status code of current shipment status",
                        "type": "string",
                        "enum": [
                            "IN_TRANSIT_TO_ORIGIN",
                            "AT_ORIGIN",
                            "IN_TRANSIT_TO_DESTINATION",
                            "DELAYED",
                            "COMPLETED"
                        ],
                        "required": true
                    }
                }
            }
                

+ Response 401 (application/json)

    + Body 
            
            { 
                "error": {
                    "code": 1001,
                    "message": "Authorization required"
                }
            }
    
+ Response 403 (application/json)

    + Body 
            
            { 
                "error": {
                    "code": 1004,
                    "message": "Access denied"
                }
            }
    
+ Response 404 (application/json)

    + Body 
            
            { 
                "error": {
                    "code": 1005,
                    "message": "Shipment not found"
                }
            }